#Practice Portfolio
name=input("Enter your name: ")
age=int(input("Enter your age: "))
nationality=input("Enter your nationality: ")
religion=input("Enter your religion: ")
address=input("Enter your address: ")
phone_number=int(input("Enter your phone number: "))
gender=input("Enter your gender (Male/Female): ")
father_name=input("Enter your father name: ")
mother_name=input("Enter your mother name: ")
print ("Your name is",name)
print ("You are",age, "years old")
print ("You are",gender)
print ("Your nationality is",nationality)
print ("You are",religion)
print ("You are",gender)
print ("You are living in", address)
print ("Your phone number is",phone_number)
print ("Your father name is",father_name)
print ("Your mother name is",mother_name)